apiVersion: v1
kind: ConfigMap
metadata:
  name: dfs-config
  namespace: distributed-file-system
data:
  CHUNK_SIZE: "1048576"
  REPLICATION_FACTOR: "2"
  STORAGE_BASE_DIR: "/app/storage_nodes"
  DOWNLOAD_DIR: "/app/downloads"
  DATABASE_PATH: "/app/db/metadata.db"