apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dfs-storage-pvc
  namespace: distributed-file-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dfs-downloads-pvc
  namespace: distributed-file-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dfs-db-pvc
  namespace: distributed-file-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi